 ---
title: "Disease risk modeling - BYM BYM2"
author: "Hashan Fernando"
date: "2024-02-13"
output: html_document
---


#### Disease risk modeling- BYM BYM2 using INLA

https://www.paulamoraga.com/book-spatial/disease-risk-modeling.html

 Modeling of lung cancer risk in Pennsylvania
```{r}
library(SpatialEpi)
data(pennLC)
class(pennLC)
```

```{r}
names(pennLC)
```

```{r}
head(pennLC$data)
```

```{r}
head(pennLC$smoking)
```

```{r}
library(sf)
map <- st_as_sf(pennLC$spatial.polygon)
countynames <- sapply(slot(pennLC$spatial.polygon, "polygons"),
                      function(x){slot(x, "ID")})
map$county <- countynames
head(map)
```
Observed cases
```{r}
library(dplyr)
d <- group_by(pennLC$data, county) %>% summarize(Y = sum(cases))
head(d)
```
Expected cases
```{r}
pennLC$data <- pennLC$data[order(pennLC$data$county,
pennLC$data$race, pennLC$data$gender, pennLC$data$age), ]
```

```{r}
E <- expected(population = pennLC$data$population,
              cases = pennLC$data$cases, n.strata = 16)
```

```{r}
d$E <- E
head(d)
```
Smokers proportions
```{r}
d <- dplyr::left_join(d, pennLC$smoking, by = "county")
```

```{r}
d$SMR <- d$Y/d$E
```

```{r}
head(d)
```
Mapping SMR
```{r}
map <- dplyr::left_join(map, d, by = "county")
```

```{r}
library(mapview)
library(RColorBrewer)
pal <- colorRampPalette(brewer.pal(9, "YlOrRd"))
mapview(map, zcol = "SMR", color = "gray", alpha.regions = 0.8,
        layer.name = "SMR", col.regions = pal,
        map.types = "CartoDB.Positron")
```

```{r}
library(mapview)
library(RColorBrewer)
library(leafpop)

pal <- colorRampPalette(brewer.pal(9, "YlOrRd"))
mapviewOptions(fgb = FALSE)

popuptable <- leafpop::popupTable(dplyr::mutate_if(map,
is.numeric, round, digits = 2),
zcol = c("county", "Y", "E", "smoking", "SMR"),
row.numbers = FALSE, feature.id = FALSE)

mapview(map, zcol = "SMR", color = "gray", col.regions = pal,
highlight = leaflet::highlightOptions(weight = 4),
popup = popuptable)
```
Model
```{r}
library(spdep)
library(INLA)
nb <- poly2nb(map)
nb2INLA("map2.adj", nb)
g <- inla.read.graph(filename = "map2.adj")
```

```{r}
map$re_u <- 1:nrow(map)
map$re_v <- 1:nrow(map)
```

```{r}
formula <- Y ~ smoking +
  f(re_u, model = "besag", graph = g, scale.model = TRUE) +
  f(re_v, model = "iid")
```

```{r}
res <- inla(formula, family = "poisson", data = map, E = E,
control.predictor = list(compute = TRUE),
control.compute = list(return.marginals.predictor = TRUE))
```

Results
```{r}
res$summary.fixed
```

```{r}
res$summary.fitted.values[1:3, ]
```

```{r}
# relative risk
map$RR <- res$summary.fitted.values[, "mean"]
# lower and upper limits 95% CI
map$LL <- res$summary.fitted.values[, "0.025quant"]
map$UL <- res$summary.fitted.values[, "0.975quant"]
```

Mapping disease risk
```{r}
library(mapview)
library(RColorBrewer)
library(leafpop)
pal <- colorRampPalette(brewer.pal(9, "YlOrRd"))
mapviewOptions(fgb = FALSE)
mapview(map, zcol = "RR", color = "gray", col.regions = pal,
highlight = leaflet::highlightOptions(weight = 4),
popup = leafpop::popupTable(dplyr::mutate_if(map, is.numeric,
                                             round, digits = 2),
zcol = c("county", "Y", "E", "smoking", "SMR", "RR", "LL", "UL"),
row.numbers = FALSE, feature.id = FALSE))
```

```{r}

```

```{r}

```


```{r}

```


```{r}

```
